micronaut:
  application:
    name: echelon-app

datasources:
  default:
    jdbc-url: jdbc:h2:mem:flywayDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: 'org.h2.Driver'

flyway:
  datasources:
    default:
      enabled: true
